services:
  madsky:
    build:
      context: .
      dockerfile: Dockerfile
    image: madsky
    container_name: madsky
    environment:
      NODE_ENV: production
    restart: unless-stopped
    networks:
      - databases
      - npm
    env_file:
      - stack.env

networks:
  databases:
    external: true
  npm:
    external: true
